# Site settings
title: LLM Verifier
description: A tool for doctors to annotate and build medical decision trajectories
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include pages
include:
  - annotation-tool.html
  - trajectory-builder.html
  - patient-llm.html

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Default layout for pages
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Navigation
header_pages:
#   - about.md
  - annotation-tool.html
  - trajectory-builder.html
  - patient-llm.html

# Google Analytics
google_analytics: # Your Google Analytics tracking ID here

# Custom styles
sass:
  custom: "assets/css/main.scss"
